version: '3.8'
services:
  postgresdb:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=ca6a70f64cef
      - PGDATA=/data/postgresql
    volumes:
      - postgres:/data/postgresql
    ports:
      - 5432:5432

  kouyou:
    build: .
    image: analytics
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb
    environment:
      - DATABASE_URL=postgresql://db:ca6a70f64cef@postgresdb:5432/analyticdb?schema=public
      - JWT_SECRET=836a68b8c286
      - PORT=8080

volumes:
  postgres:
